---

# rdiff usually runs at 21h
mysqlbackup_cron_hour: 20
mysqlbackup_cron_minute: 30
mysqlbackup_backupdir: "/var/backups/mysql"
mysqlbackup_filename_format: "{{ ansible_hostname }}-%Y%m%d-%H%M%S.mysqldump"
mysqlbackup_cnf_file: "/etc/mysql/debian.cnf"
mysqlbackup_logdir: /var/log/mysql

mysqlbackup_mysqldump_opts:
  - "--events"
  - "--triggers"
  - "--routines"
  - "--opt"

mysqlbackup_mysqldump_require_db:
  - mysql

mysqlbackup_mysqldump_ignore_db:
  - information_schema
  - performance_schema

mysqlbackup_mysqldump_logging_active: 1
mysqlbackup_mysqldump_compress_active: 1
mysqlbackup_mysqldump_monitoring_active: 1
