# Installs required tools for CiviCRM development:
# civix, nodejs, composer, git-scan, etc.
# https://civicrm.org/blogs/totten/new-46-dev-composer-and-nodejs
#
# IMPORTANT: for CiviCRM development, running tests, etc, better to
# use the Vagrant boxes. This is more to facilitate extension dev on
# production-ish servers.

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - gettext
    - git
    - bzip2
  tags:
    - packages

# Stretch does not have npm
- name: Get the nodejs repo key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  tags:
    - nodejs
    - packages

- apt_repository:
    repo='deb https://deb.nodesource.com/node_6.x stretch main'
    state=present
    update_cache=yes
  when: ansible_distribution_release == "stretch"
  tags:
    - nodejs
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - nodejs
  when: ansible_distribution_release == "stretch"
  tags:
    - nodejs
    - packages

# libssl-dev from jessie-backports required for nodejs-dev, for node-gyp, for node, for npm..
- apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    default_release: jessie-backports
  with_items:
    - libssl-dev
    - npm
  when: ansible_distribution_release == "jessie"
  tags:
    - packages

- name: civicrm | Download civix, cv, civistrings and git-scan
  get_url:
    url="https://download.civicrm.org/{{ item }}/{{ item }}.phar"
    dest="/usr/local/bin/{{ item }}"
  with_items:
    - civix
    - cv
    - civistrings
    - git-scan
  tags:
    - packages

- name: civicrm | Ensure that civicrm tools (civix, cv, etc) are executable
  file: path="/usr/local/bin/{{ item }}" mode=0755
  with_items:
    - civix
    - cv
    - civistrings
    - git-scan
  tags:
    - packages

# This isn't great, because it installs in /usr/bin/bower (not local).
- name: civicrm | Install bower using npm.
  npm: name=bower global=yes
  tags:
    - packages

