---

# Firewall (iptables)
- name: Install ufw
  apt: name=ufw state=present
  tags:
    - ufw

- name: Remove old ssh allow-all rule
  ufw: proto=tcp port=22 rule=allow delete=yes
  tags:
    - ufw

- name: Allow ssh on IPv4
  ufw: proto=tcp port=22 src="0.0.0.0/0" rule=allow
  when: ufw_ipv4_allow_ssh == true
  tags:
    - ufw

- name: Allow ssh on IPv6 only
  ufw: proto=tcp port=22 src="::/0" rule=allow
  when: ufw_ipv6_allow_ssh == true
  tags:
    - ufw

- name: Allow http
  ufw: proto=tcp port=80 rule=allow
  tags:
    - ufw

- name: Allow https
  ufw: proto=tcp port=443 rule=allow
  tags:
    - ufw

- name: Allow Munin to munin servers and monitoring servers
  ufw: proto=tcp port=4949 rule=allow src="{{ item }}"
  with_items: "{{ ufw_munin_allow_src }}"
  tags:
    - ufw

- name: Allow access to icinga2 5665 from icinga2 servers
  ufw: proto=tcp port=5665 rule=allow src="{{ item }}"
  with_items: "{{ ufw_icinga_allow_src }}"
  tags:
    - ufw
    - ufw-icinga

# UFW per-host exceptions
# see https://github.com/ansible/ansible/issues/10047 for why the weird default.
- ufw: proto="{{ item.value.proto }}" port="{{ item.value.port }}" src="{{ item.value.src }}" rule="{{ item.value.rule }}"
  with_dict: "{{ ufw_extra | default({}) }}"
  tags:
    - ufw

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny
  tags:
    - ufw

- name: Disable logging
  ufw:
    logging: off
  tags:
    - ufw

- name: Restart ufw
  service: name=ufw state=restarted
  tags:
    - ufw

- name: ufw | Deploy fail2ban jail.conf
  template: src=etc/fail2ban/jail.conf dest=/etc/fail2ban/jail.conf owner=root group=root mode=0644
  tags:
    - ufw
    - ufw-fail2ban

- name: ufw | Deploy fail2ban paths-common.conf
  template: src=etc/fail2ban/paths-common.conf dest=/etc/fail2ban/paths-common.conf owner=root group=root mode=0644
  tags:
    - ufw
    - ufw-fail2ban
