---

# Based on:
# https://github.com/openmicroscopy/ansible-role-mysql-backup/

# Required to cleanup backups after 24h
- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - tmpreaper
  tags:
    - mysqlbackup
    - packages

- name: mysqlbackup | create backup directory
  become: yes
  file:
    path: "{{ mysqlbackup_backupdir }}"
    recurse: yes
    state: directory
  tags:
    - mysqlbackup

- name: mysqlbackup | create backup tmp directory
  become: yes
  file:
    path: "{{ mysqlbackup_backupdir }}/tmp"
    recurse: yes
    state: directory
  tags:
    - mysqlbackup

- name: mysqlbackup | deploy configuration
  template:
    src="mysqldump-secure.conf"
    dest="/etc/mysqldump-secure.conf"
    owner=root group=root mode=0400
  tags:
    - mysqlbackup

- name: mysqlbackup | deploy backup script
  copy:
    src="mysqldump-secure"
    dest="/usr/local/bin/mysqldump-secure"
    owner=root group=root mode=0755
  tags:
    - mysqlbackup

- name: mysqlbackup | create cron job
  cron:
    name="mysqlbackup"
    hour="{{ mysqlbackup_cron_hour }}"
    minute="{{ mysqlbackup_cron_minute }}"
    job="/usr/local/bin/mysqldump-secure --cron"
    cron_file="mysqlbackup"
    user="root"
    state=present
  tags:
    - mysqlbackup

- name: mysqlbackup | define cron job PATH
  cron:
    name=PATH
    env=yes
    value="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
    cron_file="mysqlbackup"
    user="root"
  tags:
    - mysqlbackup
