---
- name: restart nginx
  service: name=nginx state=restarted

- name: restart apache2
  service: name=apache2 state=restarted

- name: restart mysql
  service: name=mysql state=restarted daemon_reload=yes
